---
- name: Core congfiguration for CentOS 9
  hosts: localhost
  remote_user: root

# This is a mess and needs to be re-thought.
# I suspect @server-product-environment now has GUI dependencies

  vars:
    unprivuser: support

  tasks:
  - name: Workaround libstoragemgmt dependency
    yum:
      name:
      - 'libstoragemgmt'
      state: latest
  
  - name: Install environment package groups
    yum:
      name:
      - "@server-product-environment"
      state: present
  
  - name: Install regular package groups
    yum:
      name:
      - "@development"
      - "@headless-management"
      state:  present
  
# TODO: Check these package names against OS

  - name: Install individual packages
    yum:
      name:
      - 'autofs'
      - 'bind-utils'
      - 'expat'
      - 'expat-devel'
      - 'htop'
      - 'lftp'
      - 'lsof'
      - 'ncftp'
      - 'ncurses-devel'
      - 'openssh-server'
      - 'openssl-devel'
      - 'openvm-tools'
      - 'python3-firewall'
      - 'python3-lxml'
      - 'redhat-lsb-core'
      - 'sudo'
      - 'tmpwatch'
      - 'xinetd'
      - 'zlib-devel'

  - name: Start autofs service with OS
    service:
      name: autofs
      enabled: yes
      state: started
  
  - name: Configure lftp

  - name: Create unpriviledged account
    user:
      name: "{{unprivuser}}"

  - name: Configure unpriviledged account authorized_keys
    get_url:
      url: https://blacksilverconsulting.github.io/OS9/authorized_keys
      owner: "{{unprivuser}}"
      group: "{{unprivuser}}"
      mode: "0600"
      dest: "/home/{{unprivuser}}/.ssh"
  
  - name: Disable SELinux
    ini_file:
      path: /etc/selinux/config
      section: null
      option: SELINUX
      value: disabled
      no_extra_spaces: yes
  
  # TODO The rest of the base setup.