---
- name: Core congfiguration for CentOS 9
  hosts: localhost
  remote_user: root

# This is a mess and needs to be re-thought.
# I suspect @server-product-environment now has GUI dependencies

  tasks:
  - name: Workaround for libstoragemgmt
    yum:
      name:
      - 'libstoragemgmt'
      state: latest
  
  - name: Environment package groups
    yum:
      name:
      - "@server-product-environment"
      state: present
  
  - name: Regular package groups
    yum:
      name:
      - "@development"
      - "@headless-management"
      state:  present
  
# TODO: Check these package names against OS

  - name: Individual packages
    yum:
      name:
      - 'autofs'
      - 'bind-utils'
      - 'expat'
      - 'expat-devel'
      - 'htop'
      - 'lftp'
      - 'lsof'
      - 'ncftp'
      - 'ncurses-devel'
      - 'openssh-server'
      - 'openssl-devel'
      - 'openvm-tools'
      - 'python3-firewall'
      - 'python3-lxml'
      - 'redhat-lsb-core'
      - 'sudo'
      - 'tmpwatch'
      - 'xinetd'
      - 'zlib-devel'

# Do we still need this? 

  - name: Unpriviledged support account
    user:
      name: support 
      
  # TODO The rest of the base setup.