---
- name: PostgreSQL 14 Client and Server
  hosts: localhost
  remote_user: root

  tasks:
  - name: Install PostgreSQL 14 client and server
    yum:
      name:
      - postgresql14
      - postgresql14-contrib
      - postgresql14-libs
      - postgresql14-server
      state: latest

  - name: Create PostgreSQL system-wide configuration directory
    file:
      path: /etc/sysconfig/pgsql
      state: directory
      group: root
      owner: root
      mode: 0755

  - name: Configure PostgreSQL CLI
    get_url:
      url: https://github.com/BlacksilverConsulting/OS9/raw/main/psqlrc
      dest: /etc/sysconfig/pgsql/psqlrc
      mode: 0644
      group: root
      owner: root

  - name: Add service alias for PostgreSQL 14
    file:
      src: /usr/lib/systemd/system/postgresql-14.service
      state: link
      path: /usr/lib/systemd/system/postgresql.service
  
  - name: Add PostgreSQL 14 dependency on autofs
    ini_file:
      path: /etc/systemd/system/postgresql-14.service.d/override.conf
      section: Unit
      option: after
      value: "autofs.service"
      no_extra_spaces: yes
  
  - name: Add cronjob to vacuum databases nightly
    cron:
      name: "Nightly database vacuum"
      special_time: daily
      user: postgres
      job: >
        /bin/bash -c 'for db in $(/bin/psql -AcqtX "SELECT datname FROM pg_Database WHERE datAllowCon;'); do /bin/psql -d $db -c "VACOOM ANALYZE;"; done"

  - name: Install PostgreSQL 14 Perl drivers
    yum:
      name: "perl-DBD-Pg"
      state: latest
