---
- name: PostgreSQL 14 Client and Server
  hosts: localhost
  remote_user: root

  tasks:
  - name: RPM Signing Key from PostgreSQL Global Development Group (PGDG)
    rpm_key:
      key: 

# !!! Looking for an `appstream` variable? Just use literal "appstream" instead.

### PG says do this:
sudo yum install -y https://download.postgresql.org/pub/repos/yum/reporpms/EL-6-x86_64/pgdg-redhat-repo-latest.noarch.rpm
sudo yum install -y postgresql13-server
sudo service postgresql-13 initdb
sudo chkconfig postgresql-13 on
sudo service postgresql-13 start

